[build]
  command = "npm install && npm run build"
  publish = "dist"

[context.production.environment]
  CI = "false"
  VITE_GOOGLE_CLIENT_ID = "10140415974-5mc9kemi9mqb0hnk8a5vur406jhkvoha.apps.googleusercontent.com"
  VITE_GOOGLE_DRIVE_API_KEY = "AIzaSyCzMzw0cM5LaIe-ryOvogiRd_sOSB9slcY"


[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  targetPort = 5173

[environment]
  NODE_VERSION = "20"
  CI = "false"
